pod 'TAPKeyboardPop',                   '~> 0.1.2'
#pod 'AFNetworking',                     '~> 2.6.3'
pod 'CRToast',                          '~> 0.0.9'
#pod 'MBProgressHUD',                    '~> 0.9.2'
#pod 'JDStatusBarNotification',          '~> 1.5.3'
pod 'SVProgressHUD',                    '~>2.0.3'
pod 'IQKeyboardManager',                '~> 4.0.1'
pod 'Bugly',                            '~> 2.1'
#pod 'YTKNetwork',                       '~> 1.0.0'
pod 'MJRefresh',                        '~> 3.1.0'
pod 'YLGIFImage',                       '~> 0.11'
#pod 'YYKit',                            '~> 1.0.5'
pod 'YYText',                           '~> 1.0.4'
pod 'YYModel',                          '~> 1.0.3'
pod 'Masonry',                          '~> 1.0.0'
pod 'SDAutoLayout',                     '~> 1.52'
pod 'BlocksKit',                        '~> 2.2.5'
pod 'SDVersion',                        '~> 2.6'
pod 'UMengSocial',                      '~> 5.0'
pod 'RegExCategories',                  '~> 1.0'
pod 'SDWebImage',                       '~> 3.7'
pod 'HYBNetworking',                    '~> 3.0.0'
pod 'Typeset',                          '~> 3.2.0'
pod 'Aspects',                          '~> 1.4.1'
pod 'LKDBHelper', :head
